name: Auto Release

on:
  push:
    branches: [main, master, develop]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get latest EXE name
        id: exe
        run: |
          EXE_NAME=$(git log --all --oneline | head -1 | awk '{print $1}')
          echo "name=journey_bot_v${EXE_NAME}.exe" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tool
          release_name: Auto build - Junk Code + PyArmor + Nuitka
          draft: false
          prerelease: false
